# Generated by Django 3.1.4 on 2020-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201230_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Writer')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.TextField(default=''),
        ),
    ]
