# Generated by Django 3.1.4 on 2020-12-30 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Job Types',
            },
        ),
        migrations.CreateModel(
            name='PremiumJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Premium jobs',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Subject Types',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.IntegerField(default=10)),
                ('company', models.TextField(default='')),
                ('company_url', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('deadline', models.DateTimeField()),
                ('brief', models.TextField(default='')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected')], null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobtype')),
                ('premium_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.premiumjob')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
