# Generated by Django 3.1.4 on 2020-12-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobtype_order_premiumjob_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumjob',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
